[package]
publish = false
name = "ic-auth-client"
authors = ["Perforate Foundation"]
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
ic-agent = { version = "0.37.1", features = ["wasm-bindgen"] }
base64 = "0.22.1"
gloo-console = "0.3.0"
gloo-events = "0.2.0"
gloo-timers = "0.3.0"
gloo-utils = "0.2.0"
ring = { version = "0.17.8", features = ["wasm32_unknown_unknown_js"] }
serde = { version = "1.0.19", features = ["derive"] }
serde_json = "1.0.117"
serde-wasm-bindgen = "0.6.4"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
wasm-timer = "0.2.5"
web-sys = { version = "0.3.69", default-features = false, features = [
    "Window",
    "EventListener",
    "Location",
    "MessageEvent",
    "Storage",
    "Url",
    "console",
    "History",
    "CryptoKey",
    "CryptoKeyPair",
] }

[dev-dependencies]
serde_test = "1.0.177"
wasm-bindgen-test = "0.3.43"
