[build]
target = "crates/frontend/index.html"
dist = "dist/frontend"

[watch]
watch = ["crates/frontend", "crates/shared"]
ignore = ["crates/frontend/style/tw_output.css"]

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = [
    "-c",
    "cd crates/frontend && npx tailwindcss -i style/tw_input.css -o style/tw_output.css --minify",
]
